#listen: '127.0.0.1:8080'
listen: 'SERVER_STARTER'
balancing_method: 'leastreq'
access_log:
  format: 'ltsv'
  path: '/dev/stdout'
  fields: ['time', 'status', 'size', 'reqtime_nsec', 'backend']
healthcheck:
  path: '/'
  interval: '1s'
  rise_count: 2
  fall_count: 2
backends:
- url: 'http://127.0.0.1:9000'
  weight: 1
- url: 'http://127.0.0.1:9001'
  weight: 2
read_timeout: 10s
write_timeout: 10s