listen: '127.0.0.1:8080'
balancing_method: 'leastreq'
healthcheck:
  path: '/'
  interval: '1s'
  rise_count: 5
  fall_count: 5
backends:
- url: 'http://127.0.0.1:9000'
  weight: 1
- url: 'http://127.0.0.1:9001'
  weight: 2