# listen: Addr and port to listen (required)
#   If it has "SERVER_STARTER:" prefix, fd passed by https://github.com/lestrrat/go-server-starter will be used
# e.g.
#   127.0.0.1:8080
#   SERVER_STARTER:0.0.0.0:8080
#   SERVER_STARTER:/path/to/socket
listen: '127.0.0.1:8080'

# balancing_method: Method to balance requests to backends (required)
#   Currently, "leastreq" method is the only supported.
#   "leastreq" method selects a backend which have the least outstanding requests
balancing_method: 'leastreq'

# access_log (optional)
access_log:
  format: 'ltsv'
  path: '/dev/stdout'
  fields: ['time', 'time_nsec', 'status', 'size', 'reqtime_nsec', 'backend', 'path', 'query', 'method']

# error_log (required)
log:
  path: '/dev/stderr'
  level: 'debug'

# heathcheck: Healthcheck to determine whether backends are alive or dead (required)
healthcheck:
  path: '/'
  interval: '10s'
  # rise_count: If consecutive rize_count checks are passed, the backend will be marked as 'alive'
  rise_count: 2
  # fall_count: If consecutive fall_count checks are not passed, the backend will be marked as 'dead'
  fall_count: 2
  # state_file: TSV file to store current health state of backends
  #   Initial backend state after launching will be loaded from state_file
  state_file: './tmp/health_state.tsv'

# backends: Servers to process actual requests (required)
backends:
- url: 'http://127.0.0.1:9000'
  weight: 1
- url: 'http://127.0.0.1:9001'
  weight: 2

# backend_url_header: If this is set, responses for clients include URL of a backend processing the request. (optional)
backend_url_header: 'x-simproxy-backend'

# max_idle_conns: the maximum idle (keep-alive) connections to keep (optional)
max_idle_conns: 100

# max_idle_conns_per_host: the maximum idle (keep-alive) connections to keep per-host (optional)
max_idle_conns_per_host: 16

# shutdown_timeout: timeout for shutting down HTTP server (optional)
#   On SIGTERM, Simproxy will try to shut down the server gracefully.
#   If shutdown_timeout is over, the server will be shutted down forcibly.
shutdown_timeout: 10s

# HTTP server timeout options (optional)
# see: https://golang.org/pkg/net/http/#Server
read_timeout: 10s
read_header_timeout: 10s
write_timeout: 10s

# append_x_forwarded_for (optional)
#   If true, Simproxy will append client IP to X-Forwarded-For header for backend request
append_x_forwarded_for: true

# pprof_addr: enable pprof/http for profiling (optional)
pprof_addr: '127.0.0.1:6060'

# enable_buffer_pool: enable buffer pool for copying response
#   If true, buffer ([]byte) will be reused for multiple responses
enable_buffer_pool: false

# http_api_addr: listen address for HTTP API endpoint
http_api_addr: '127.0.0.1:8090'

# shutdown_delay: delay shutting down
#   This is useful for restarting gracefully by a software like server-starter
shutdown_delay: 1s
